### ISSUE TITLE
Paste errors with "Shape not valid"

### ISSUE THREAD

**Issue by darkadams** [thebigsmileXD/MagicWE2#153]
When I do //copy spawn and it works but then u do paste spawn it says shape not valid.

**Comment by Bradleii** [comment]
how do i fix this

**Comment by thebigsmileXD** [comment]
- create a fork
- switch to cleanup branch
- apply fixes to the API::copy function

**Comment by Bradleii** [comment]
ok how to fix looks like you are missing a argument or using the command wrong when //copy pvp what do i need to do in //paste?

**Comment by inxomnyaa** [comment]
Copy + Paste need a full rewrite. The CopyClipboard is terrible in both design and performance
