### ISSUE TITLE
[Bug] Session error with unloaded worlds

### ISSUE THREAD

**Issue by Erkam246** [thebigsmileXD/MagicWE2#172]
Error occurs on first join after restart

**Comment by Erkam246** [comment]
I would prefer to load or set level to default level if level is null

**Comment by inxomnyaa** [comment]
Please provide proper information - Try the //bug or //report command, so you get a pre-filled issue with the plugin information, or post the console output of //info here

**Comment by inxomnyaa** [comment]
I would like to help you on this issue + know how to reproduce it, so i can solve it, but i need some further information

**Comment by inxomnyaa** [comment]
> I would prefer to load or set level to default level if level is null

Oh dayumn, probably caused by session restore :o I think i understand the error behind that now

**Comment by inxomnyaa** [comment]
Confirmed to appear when a session is restored
Steps to reproduce:
* Load a world that is not automatically loaded
* Create a selection in that world
* Restart the server
* Join
What happens:
* Session is read from json
* The level name of the last selection is read
* Session tries to construct the selection again
* The world is not loaded, so `getLevelByName()` returns null
* Error is thrown: `TypeError: "Argument 2 passed to xenialdan\MagicWE2\selection\Selection::__construct() must be an instance of pocketmine\level\Level, null given, called in /home/mcpe/bauserver/plugins/MagicWE2-cleanup/src/xenialdan/MagicWE2/helper/SessionHelper.php on line 228" (EXCEPTION) in "plugins/MagicWE2-cleanup/src/xenialdan/MagicWE2/selection/Selection" at line 52`
---
For now i am unsure how i want that fixed, there are 2 options:
* Automatically load the level
* Tell the user that the level is not loaded + the selection can not be restored
If i do the second option, i could also allow restoring the selection if the world gets loaded (and no new selections were made)

**Comment by Aericio** [comment]
long ass title bruh

**Comment by inxomnyaa** [comment]
I will still probably add the option to automatically load in the selection if you load the level.
