### ISSUE TITLE
[Bug] Language

### ISSUE THREAD

**Issue by MonoAdrian23** [thebigsmileXD/MagicWE2#174]
At First sorry for my bad english.
Language is Set to german but plugin language is already english.
Join Message is MagicWe2 Language was set to english.

MagicWe Latest 
Pocketmine 3.11.4

I hope you can help me please.
Thanks for this good Plugin!

**Comment by inxomnyaa** [comment]
Duplicate of #173 , i hope that will clarify the issue for you ^^
