### ISSUE TITLE
[Question] Where is stable release?

### ISSUE THREAD

**Issue by Nerahikada** [thebigsmileXD/MagicWE2#176]
I am sorry for this question.
The feature-flip-rotate branch seems to be updated frequently, but the default branch is cleanup.
Which version should I download?

**Comment by Aericio** [comment]
Which one are you currently using?

**Comment by Nerahikada** [comment]
I am using `feature-flip-rotate`.

**Comment by inxomnyaa** [comment]
The most stable build should be the latest build from https://github.com/thebigsmileXD/MagicWE2/tree/phpstan or https://github.com/thebigsmileXD/MagicWE2/tree/experimental-blockstate-testing
I know i fixed copy & paste in one of those branches and then moved on to the next feature, but i am not sure if i merged the changes into cleanup..

EDIT: this commit fixed clipboards: https://github.com/thebigsmileXD/MagicWE2/commit/73b9ec1be5b5766d76bb751ba5e23b455c9b4b97

Stable build: https://poggit.pmmp.io/ci/thebigsmileXD/MagicWE2/~/dev:279

**Comment by teracube** [comment]
Any poggit release version soon ?

**Comment by inxomnyaa** [comment]
Probably soon.

**Comment by inxomnyaa** [comment]
Release now published on GitHub: https://github.com/thebigsmileXD/MagicWE2/releases/tag/v10.0.1

**Comment by teracube** [comment]
Release is not the latest cleanup build dev-326 but older dev-279
Exact ?
thanks

https://poggit.pmmp.io/r/75481/MagicWE2_dev-279.phar
https://poggit.pmmp.io/r/84438/MagicWE2_dev-326.phar

**Comment by inxomnyaa** [comment]
New release for PM 3.13: https://github.com/thebigsmileXD/MagicWE2/releases/tag/v10.0.2
PM3 is now discontinued

**Comment by inxomnyaa** [comment]
Stable for PM4: https://poggit.pmmp.io/ci/thebigsmileXD/MagicWE2/MagicWE2/dev:431

**Comment by inxomnyaa** [comment]
New stable PM4 build https://poggit.pmmp.io/ci/thebigsmileXD/MagicWE2/MagicWE2/dev:477 - but this includes assets which are currently WIP #221 
On production servers i highly suggest blocking the `/asset` command.
