### ISSUE TITLE
[10.0.2] Commands always require flags

### ISSUE THREAD

**Issue by Nerahikada** [thebigsmileXD/MagicWE2#177]
### Description

According to the command help, the flags are optional, but if the command has no flags, an error will occur.

Example command: ```//set stone```
Output: 
```
[MagicWE2] Looks like you are missing an argument or used the command wrong!
[MagicWE2] Undefined index: flags
//set <blocks:string> [flags:text]
```

---
| MagicWE2 v10.0.2 | Information |
| --- | --- |
| Website | https://github.com/thebigsmileXD/MagicWE2 |
| Version | 10.0.2 |
| Plugin API Version | 3.9, 3.10, 3.11 |
| Authors | XenialDan |
| Enabled | Yes |
| Uses UI | No |
| Phar | Yes |
| PMMP Protocol Version | v1.14.0 |
| PMMP Version | 3.11.6 |
| PMMP API Version | 3.11.6 |

**Comment by Aericio** [comment]
@thebigsmileXD said that he was in the progress of removing flags.

**Comment by inxomnyaa** [comment]
I thought i patched that issue for all commands.
> removing flags.

Reason for that is that the current code is still in cleanup, and flags do only create trouble right now, and slow down development.
If i find a good way to add those back (and add masks/filters/palettes), they will probably return, more powerful than ever.

I'll look into the issue

**Comment by inxomnyaa** [comment]
Is patched in PM4
