### ISSUE TITLE
[10.0.2] Duplicate Exclamation Mark

### ISSUE THREAD

**Issue by Nerahikada** [thebigsmileXD/MagicWE2#180]
### Description

The exclamation mark in the message is duplicated.
This affects translation.
![temp](https://user-images.githubusercontent.com/15967582/77818033-a3391a80-7112-11ea-9970-7cfb05e59aa7.png)

---
| MagicWE2 v10.0.2 | Information |
| --- | --- |
| Website | https://github.com/thebigsmileXD/MagicWE2 |
| Version | 10.0.2 |
| Plugin API Version | 3.9, 3.10, 3.11 |
| Authors | XenialDan |
| Enabled | Yes |
| Uses UI | No |
| Phar | Yes |
| PMMP Protocol Version | v1.14.0 |
| PMMP Version | 3.11.6 |
| PMMP API Version | 3.11.6 |

**Comment by Aericio** [comment]
Location: https://github.com/thebigsmileXD/MagicWE2/blob/f102dddd7c580ac728cd13b861bc652bf9d51033/src/xenialdan/MagicWE2/session/UserSession.php#L114

**Comment by Aericio** [comment]
Appears the exclamation mark isn't supposed to be there in `eng.ini` (considering the color reset).

You can just remove it from `eng.ini`, search for `tool.wand.setenabled`.

**Comment by Aericio** [comment]
Also, your commit would break the plugin.

**Comment by Nerahikada** [comment]
The message should look like this and modify the plugin.
```
The wand tool is now <GREEN>enabled<RESET>!
```

For example, in Japanese, words appear between sentences.
In that case, the message will look bad.
https://github.com/Nerahikada/MagicWE2/blob/798381c14b12fba0bd104dacd934f95eea0a9612/resources/lang/jpn.ini#L79

**Comment by Nerahikada** [comment]
The plugin in the cleanup branch is already broken.
4c685171f5e52c9b338f623ffed08c6017376e38

**Comment by inxomnyaa** [comment]
> For example, in Japanese, words appear between sentences.
Darn, i only was waiting for that to happen. Sadly, this is a limitation of translations, no easy fix for that.
The colors are hardcoded, i didn't want them to be inside translations to remove confusion for first time contributors.

Fix to the issue will be out soon

**Comment by inxomnyaa** [comment]
Took me long enough
