### ISSUE TITLE
[10.0.2] Paste multi-world issue

### ISSUE THREAD

**Issue by Nerahikada** [thebigsmileXD/MagicWE2#185]
### Description
Multi world copy paste is not working.
It seems that the same problem as #30 (#57) is occurring.

I confirmed the problem with dev-279 and dev-323.

Perhaps this problem is caused by this code.
https://github.com/thebigsmileXD/MagicWE2/blob/4c685171f5e52c9b338f623ffed08c6017376e38/src/xenialdan/MagicWE2/task/AsyncPasteTask.php#L172

---
| MagicWE2 v10.0.2 | Information |
| --- | --- |
| Website | https://github.com/thebigsmileXD/MagicWE2 |
| Version | 10.0.2 |
| Plugin API Version | 3.9, 3.10, 3.11 |
| Authors | XenialDan |
| Enabled | Yes |
| Uses UI | No |
| Phar | Yes |
| PMMP Protocol Version | v1.14.60 |
| PMMP Version | 3.12.0 |
| PMMP API Version | 3.12.0 |

**Comment by inxomnyaa** [comment]
Good find o.O

No idea why it worked for me though. New selection should contain paste level

Will debug and fix asap

**Comment by inxomnyaa** [comment]
Alot of code has changed and i moved on to PM4 - can you still replicate this issue?

**Comment by Nerahikada** [comment]
I could confirm this problem with dev431.

**Comment by inxomnyaa** [comment]
Fixed by https://github.com/thebigsmileXD/MagicWE2/commit/9cf30304a17593a2bc2c4c46f8d0b6e567c56f52#diff-a496283a147245056209ba90bfcf470faf331f59c7b3f5e1a298dcbd75c7182aR69
