### ISSUE TITLE
Copy/Paste Bug, after copy, paste doese not work correctly[Bug]

### ISSUE THREAD

**Issue by suerion** [thebigsmileXD/MagicWE2#188]
### Description
First Problem:
After Copying 28500 Blocks, i would Paste it, they does not Paste correctly.

I had copyied the road also, but it does not paste it.

Second Problem:
After Copying, it does not found some infos in the clipboard

here you could find the Pictures
https://imgur.com/a/IJG8GzX

//wand
pos1
pos2
//copy
Asynchronous Copying finished, (25800 Blocks)
Flying to the other Position
//paste
Asynchronous Pasting finished, (2300 Blocks from 25800)

Second Thing:
//wand
pos1
pos2
//copy
Asynchronous Copying finished, (65000 Blocks)
Flying to the other Position
//paste
No Files in the Clipboard

---

| MagicWE2 | Information |
| --- | --- |
| Version | Latest Stable Version |
| PMMP Protocol Version | 390 |
| PMMP Version | 3.12.5 |

**Comment by inxomnyaa** [comment]
Latest Stable Version is an invalid version identifier. Update the issue or comment with the output of `//version`

Closing as invalid.

**Comment by inxomnyaa** [comment]
Turn on debug level 2 in pocketmine.yml and check console for "Out of Memory" issues. Make sure your permissions are set up correctly (had been changed in the stable releases)

**Comment by suerion** [comment]
Oh sorry, you had added an new release, my version was 10.0.1
