### ISSUE TITLE
[FR] Add translation to spanish language

### ISSUE THREAD

**Issue by JukMR** [thebigsmileXD/MagicWE2#207]
Hi! I would like to add a translation to the spanish language. Could that be possible? Cheers!

**Comment by JukMR** [comment]
I would be following the rules described in #130.

**Comment by inxomnyaa** [comment]
https://github.com/thebigsmileXD/MagicWE2/blob/PM4/resources/lang/esp.ini already exists. Feel free to enhance it. Closing issue as it adds no value
