### ISSUE TITLE
[Bug] Breaking a block causes an error

### ISSUE THREAD

**Issue by NekoFuwa1739** [thebigsmileXD/MagicWE2#224]
| MagicWE2 | Information |
| --- | --- |
| Version | Build 479 |
| Plugin API Version | 4.0.0 |
| PMMP Protocol Version | 431 |
| PMMP Version | 4.0.0+dev |
| PMMP API Version | 4.0.0 |

Breaking a block causes an error
![Screenshot_20210524-013056_Termius](https://user-images.githubusercontent.com/62869023/119268980-54ace080-bc30-11eb-8f66-77778035e02f.jpg)

**Comment by inxomnyaa** [comment]
Do you use PHP8? I forgot to upgrade the required version to PHP8 in the plugin.yml

**Comment by inxomnyaa** [comment]
PHP8 is required now
