### ISSUE TITLE
[FR] ScoreFactory & Bossbar

### ISSUE THREAD

**Issue by AIPTU** [thebigsmileXD/MagicWE2#226]
**Describe the feature you want here**
**Related issues and pull requests**

**Suggestions**
Can you add a command if there is a ScoreFactory or Bossbar class to disable or enable the feature like ScoreHud command? because some users might be a little annoyed, and please remove the var_dump function so there won't be too many messages in console.

[MagicWE2] Information
| Version | 10.1.5 |
| Plugin API Version | 4.0.0 |
| Authors | XenialDan |
| Enabled | Yes |
| Uses UI | Yes |
| Uses ScoreFactory | Yes |
| Phar | Yes |
| PMMP Protocol Version | v1.17.0 |
| PMMP Version | 4.0.0+dev |
| PMMP API Version | 4.0.0 |

**Comment by inxomnyaa** [comment]
//togglewaila
//togglesidebar

**Comment by AIPTU** [comment]
//togglewaila Just disable it bossbar and not scoreboard too, please add it

**Comment by inxomnyaa** [comment]
They are both added.

**Comment by AIPTU** [comment]
I only found the command to disable the bossbar which is //togglewaila and it doesn't disable the scoreboard, what is the command to disable it?

**Comment by inxomnyaa** [comment]
//togglesidebar
//mwe should help you next time..
Also the commands show autocompletion so entering //toggle should already show you both these options

**Comment by AIPTU** [comment]
Unknown command.

**Comment by inxomnyaa** [comment]
Seems to not be uploaded

**Comment by AIPTU** [comment]
Lol
