### ISSUE TITLE
[TODO] Ditch customui for FormAPI

### ISSUE THREAD

**Issue by inxomnyaa** [thebigsmileXD/MagicWE2#229]
**Description:**
As i recently archived customui

**Comment by TheNewHEROBRINEX** [comment]
Why not [pmforms](https://github.com/dktapps-pm-pl/pmforms/)? It also has form response validation

**Comment by inxomnyaa** [comment]
Because i wanted labels. I might copy the validation code over to the fork https://github.com/WolvesFortress/formapi
