### ISSUE TITLE
[10.1.6] Error thrown when trying to use blocks that are not in the r12 blockstates table

### ISSUE THREAD

**Issue by Joshiiiii** [thebigsmileXD/MagicWE2#232]
### Description
Please support costum blocks or at least ignore them.
![Screenshot_2289](https://user-images.githubusercontent.com/49375131/126899469-b6978421-f97b-4bf2-b25e-9d24f45a61d8.png)

---
| MagicWE2 v10.1.6 | Information |
| --- | --- |
| Website | https://github.com/thebigsmileXD/MagicWE2 |
| Version | 10.1.6 |
| Plugin API Version | 4.0.0 |
| Authors | XenialDan |
| Enabled | Yes |
| Uses UI | Yes |
| Uses ScoreFactory | Yes |
| Phar | Yes |
| PMMP Protocol Version | v1.17.10 |
| PMMP Version | 4.0.0+dev |
| PMMP API Version | 4.0.0 |

**Comment by inxomnyaa** [comment]
Issue is caused by always checking the blockstates list, even if no states are given. Skipping this step may improve parsing performance.

**Comment by inxomnyaa** [comment]
Appears the fault is not the `BlockStatesParser::fromString()`, whoops.
