### ISSUE TITLE
[Bug] Player Session

### ISSUE THREAD

**Issue by AIPTU** [thebigsmileXD/MagicWE2#233]
### Description

When the player leaves the server causing this problem
[Wed_Aug_25-01.30.29-UTC_2021.log](https://github.com/thebigsmileXD/MagicWE2/files/7047653/Wed_Aug_25-01.30.29-UTC_2021.log)

---

| MagicWE2 | Information |
| --- | --- |
| Version | 10.1.7 |
| Plugin API Version | 4.0.0 |
| PMMP Protocol Version | 448 |
| PMMP Version | 4.0.0 |
| PMMP API Version | 4.0.0 |

**Comment by inxomnyaa** [comment]
This appears to be an issue caused by an oversight in PM.
Try deleting the sessions folder for now

**Comment by inxomnyaa** [comment]
This should be patched now, but the ScoreFactory repo moved.
TODO: update `.poggit.yml` once the ifera repo builds

**Comment by inxomnyaa** [comment]
This is definitely patched in the latest builds as ScoreFactory changed things and throws an exception instead, which is caught.
