### ISSUE TITLE
[Bug]Server Crash with wand Axe

### ISSUE THREAD

**Issue by PocketMiner92** [thebigsmileXD/MagicWE2#248]
### Description

 I use //wand and rightclick for First Pos.
Server is crashed

---

| MagicWE2 | Information |
| --- | --- |
| Version | Dev 546 |
| Plugin API Version |  (4.0.0) |
| PMMP Protocol Version | 475 |
| PMMP Version | 4.0.3 |
| PMMP API Version | 475 |

**Comment by PocketMiner92** [comment]
[Sat_Dec_18-13.46.28-CET_2021.log](https://github.com/thebigsmileXD/MagicWE2/files/7739253/Sat_Dec_18-13.46.28-CET_2021.log)

**Comment by inxomnyaa** [comment]
Unconfirmed

**Comment by inxomnyaa** [comment]
Removed the method as it is useless
