### ISSUE TITLE
[10.2.0] 

### ISSUE THREAD

**Issue by GhostGamingTM** [thebigsmileXD/MagicWE2#249]
### Description

---
| MagicWE2 v10.2.0 | Information |
| --- | --- |
| Website | https://github.com/thebigsmileXD/MagicWE2 |
| Version | 10.2.0 |
| Plugin API Version | 4.0.0 |
| Authors | XenialDan |
| Enabled | Yes |
| Uses UI | Yes |
| Uses ScoreFactory | Yes |
| Phar | Yes |
| PMMP Protocol Version | v1.18.0 |
| PMMP Version | 4.0.5 |
| PMMP API Version | 4.0.5 |

**Comment by GhostGamingTM** [comment]
this happens everytime i use the //pos1 command and make my server crash

**Comment by inxomnyaa** [comment]
Crashdump
